"use client";

import React from "react";
 
export default function Fomo() {
  

  return (
    <div className="bg-[url('/xbotbg.png')] bg-cover bg-center bg-fixed h-screen w-full overflow-x-hidden overflow-y-scroll">
      <div className="flex flex-col min-h-screen overflow-y-auto">
        <div
          className="
         flex flex-col gap-4 items-center justify-center pt-28"
        >
          <div className="w-[55%] my-2">
            <img
              src="/xbotbanner.png"
              alt="xbotbanner image"
              width={100}
              height={100}
              className="w-full"
            />
        
        </div>
        </div>
           <div className="container mx-auto w-[85%]">
        
              <div className="bg-black bg-opacity-90 text-gray-300 p-4 flex flex-col items-center">
                <h2 className="w-max text-2xl font-semibold mb-4  inline-block">
                Meet XBot 🐳🤖
                </h2>
                <p>
                A Community-Driven, Revenue-Generating Dynamo.

                </p>
                <p>
                XBot is a user of the Original BNB Miner, just like the rest of us, except his account is community-owned and operated. A key difference? He's the sole beneficiary of income generated by an expansive array of ecosystem-wide DeFi products and services.
                </p>

               <p>This includes lucrative areas such as decentralized gaming (GameFi), decentralized finance platforms offering lending and yield farming, cross-chain quick-swap services, crypto launchpads, and specialized crypto promotional services, among others.

</p>
               <p>The potential revenue-generating avenues across these sectors are both vast and continuously expanding, ensuring a profitable and sustainable future.

</p>
               <p>Unlike typical owners of multimillion- and billion-dollar services, XBOT doesn't selfishly hoard his earnings. Instead, he reinvests them by hiring miners in the Original BNB Miner, creating a snowball effect of daily BNB that grows continually to benefit his supporters.

</p>
              </div>
          
           </div>
           <div className="w-[25%] mx-auto my-2">
            <img
              src="/commingsoon.png"
              alt="xbotbanner image"
              width={100}
              height={100}
              className="w-full"
            />
        
        </div>
      </div>
    </div>
  );
}
