 
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
 import { AppProvider } from './context/AppContext'; // Context provider for your app
import Header from "./components/Header"
import Sidebaropen from "./components/Sidebaropen"
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
           <AppProvider>
            <Header/>
            <Sidebaropen/>
            {children}
            </AppProvider>
       </body>
    </html>
  );
}
